<package format="3">
  <name>ei_whistle_cpp</name>
  <version>0.0.1</version>
  <description>Edge Impulse whistle detection</description>

  <maintainer email="Gonzab18@my.erau.edu">You</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

</package>
